=== radio-astro/casa/darwin13port/gcwrap/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://casa.nrao.edu/schema/psetTypes.html" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:editix="http://casa.nrao.edu/schema/psetTypes.html">
	<xsd:element name="casaxml">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="task" maxOccurs="unbounded"/>
				<xsd:element ref="tool" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="tool">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="code" minOccurs="0"/>
				<xsd:element ref="shortdescription"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0"/>
				<xsd:element ref="needs" minOccurs="0"/>
				<xsd:element ref="comment" minOccurs="0"/>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="method" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="module" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="method">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="return" minOccurs="0"/>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="input" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="example">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="returns">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="input">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="description">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="li" minOccurs="0"/>
				<xsd:element ref="B" minOccurs="0"/>
				<xsd:element ref="sup" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="sub" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="I" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="shortdescription">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="allowed" minOccurs="0"/>
				<xsd:element ref="choice" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="range" minOccurs="0"/>
				<xsd:element ref="descrition" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
			<xsd:attribute name="units" type="xsd:string"/>
			<xsd:attribute name="mustexist" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="any">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="limittypes" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="code">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
				<xsd:element ref="private"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="private">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="include" type="xsd:string"/>
	<xsd:element name="keyword" type="xsd:string"/>
	<xsd:element name="choice" type="xsd:string"/>
	<xsd:element name="link">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="anchor" type="xsd:string" use="required"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="return">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="allowed">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="kind" type="xsd:string"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="comments">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="range">
		<xsd:complexType>
			<xsd:attribute name="min" type="xsd:string" use="required"/>
			<xsd:attribute name="max" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="output">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="param" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="sub" type="xsd:string"/>
	<xsd:element name="sup" type="xsd:string"/>
	<xsd:element name="needs" type="xsd:string"/>
	<xsd:element name="comment">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="descrition" type="xsd:string"/>
	<xsd:element name="task">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="shortdescription" maxOccurs="unbounded"/>
				<xsd:element ref="input"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="category" type="xsd:string" use="required"/>
			<xsd:attribute name="visibility" type="xsd:string"/>
			<xsd:attribute name="async" type="xsd:string"/>
			<xsd:attribute name="startup" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="constraints">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="when" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="when">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="notequals" minOccurs="0"/>
				<xsd:element ref="equals" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="equals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="default" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="default">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="notequals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="default" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="em" type="xsd:string"/>
</xsd:schema>

=== radio-astro/casa/Pipeline-Cycle3-R2-B/pipeline/hif/cli/hif_rawflagchans.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="hif_rawflagchans" category="pipeline">
<shortdescription>Flag deviant baseline/channels in raw data</shortdescription>
<description>
Flag deviant baseline/channels in raw data.
</description>
<input>
    <param type="stringArray" name="vis" subparam="true">
        <description>List of input measurement sets</description>
        <value></value>
    </param>

    <param type="string" name="spw" subparam="true">
        <description>Set of data selection spectral windows, \'\' for all</description>
        <value></value>
    </param>

    <param type="string" name="intent" subparam="true">
        <description>Data selection intent: default is first of BANDPASS, PHASE or AMPLITUDE to have data</description>
        <value></value>
    </param>

    <param type="bool" name="flag_hilo">
        <description>True to flag outlier baseline/channels</description>
        <value>True</value>
    </param>

    <param type="double" name="fhl_limit" subparam="true">
        <description>Flag baseline/channels further from median than limit * MAD</description>
        <value>20.0</value>
    </param>

    <param type="double" name="fhl_minsample" subparam="true">
        <description>Minimum number of points in sample</description>
        <value>5</value>
    </param>

    <param type="bool" name="flag_bad_quadrant">
        <description>True to flag bad quadrants in antennas</description>
        <value>True</value>
    </param>

    <param type="double" name="fbq_hilo_limit" subparam="true">
        <description>Note as \'suspect\' baseline/channels further from median than limit * MAD</description>
        <value>8.0</value>
    </param>

    <param type="double" name="fbq_antenna_frac_limit" subparam="true">
        <description>Flag antenna quadrant if its fraction of \'suspect\' baseline/channels > limit</description>
        <value>0.2</value>
    </param>

    <param type="double" name="fbq_baseline_frac_limit" subparam="true">
        <description>Flag baseline quadrant if its fraction of \'suspect\' baseline/channels > limit</description>
        <value>1.0</value>
    </param>

    <param type="string" name="pipelinemode">
        <description>The pipeline operations mode</description>
        <value>automatic</value>
        <allowed kind="enum">
            <value>automatic</value>
            <value>interactive</value>
            <value>getinputs</value>
        </allowed>
    </param>

    <param type="bool" name="dryrun" subparam="true">
        <description>Run the task (False) or list commands(True)</description>
       <value>False</value>
    </param>

    <param type="bool" name="acceptresults" subparam="true">
        <description>Automatically apply results to context</description>
        <value>True</value>
    </param>

    <constraints>
        <when param="pipelinemode">
            <equals type="string" value="automatic" />
            <equals type="string" value="interactive">
                <default param="vis"><value type="stringArray"></value></default>
                <default param="dryrun"><value type="bool">False</value></default>
                <default param="acceptresults"><value type="bool">True</value></default>
            </equals>
            <equals type="string" value="getinputs">
                <default param="vis"><value type="stringArray"></value></default>
            </equals>
        </when>

        <when param="flag_hilo">
            <equals type="bool" value="True">
                <default param="fhl_limit"><value>20.0</value></default>
                <default param="fhl_minsample"><value>5</value></default>
            </equals>
            <equals type="bool" value="False">
            </equals>
        </when>

        <when param="flag_bad_quadrant">
            <equals type="bool" value="True">
                <default param="fbq_hilo_limit"><value>8.0</value></default>
                <default param="fbq_antenna_frac_limit"><value>0.2</value></default>
                <default param="fbq_baseline_frac_limit"><value>1.0</value></default>
            </equals>
            <equals type="bool" value="False">
            </equals>
        </when>

    </constraints>
</input>

<output>
    <param type="any" name="results">
        <description>The output results object</description>
        <any type="variant"/>
        <value></value>
    </param>
</output>
<returns type="void"/>

<example>

hif_rawflagchans flags deviant baseline/channels in the raw data. 

The flagging views used are derived from the raw data for the specified 
intent - default the first of BANDPASS, PHASE and AMPLITUDE to have data. 

Bad baseline/channels are flagged for all intents, not just the
one that is the basis of the flagging views.

For each spectral window the flagging view is a 2d image with axes 
'channel' and 'baseline'. The pixel for each channel,baseline is the 
time average of the underlying unflagged raw data.

The baseline axis is labelled by numbers of form id1.id2 where id1 and id2
are the IDs of the baseline antennas. Both id1 and id2 run over all 
antenna IDs in the observation. This means that each baseline is shown 
twice but has the benefit that 'bad' antennas are easily identified by 
eye.

Three flagging methods are available:

If parameter flag_hilo is set True then outliers from the median
of each flagging view will be flagged.

If parameter flag_bad_quadrant is set True then a simple 2 part 
test is used to check for bad antenna quadrants and/or bad baseline 
quadrants. Here a 'quadrant' is defined simply as one quarter of the
channel axis. The first part of the test is to note as 'suspect' those
points further from the view median than fbq_hilo_limit * MAD.
The second part is to flag entire antenna/quadrants if their
fraction of suspect points exceeds fbq_antenna_frac_limit. 
Failing that, entire baseline/quadrants may be flagged if their 
fraction of suspect points exceeds fbq_baseline_frac_limit. 
Suspect points are not flagged unless as part of a bad antenna or 
baseline quadrant. 

Keyword arguments:

pipelinemode -- The pipeline operating mode. In 'automatic' mode the pipeline
   determines the values of all context defined pipeline inputs automatically.
   In interactive mode the user can set the pipeline context defined parameters
   manually.  In 'getinputs' mode the user can check the settings of all
   pipeline parameters without running the task.
   default: 'automatic'.

---- pipeline parameter arguments which can be set in any pipeline mode

flag_hilo -- True to flag channel/baseline data further from the view
             median than fhl_limit * MAD.
    default: True

fhl_limit -- If flag_hilo is True then flag channel/baseline data
             further from the view median than fhl_limit * MAD.
    default: 20

fhl_minsample -- Do no flagging if the view median and MAD are derived
                 from fewer than fhl_minsample view pixels.
    default: 5

flag_bad_quadrant -- True to search for and flag bad antenna quadrants
                     and baseline quadrants. Here a /'quadrant/' is one 
                     quarter of the channel axis.
    default: True

fbq_hilo_limit -- If flag_bad_quadrant is True then channel/baselines
                  further from the the view median than fbq_hilo_limit
                  * MAD will be noted as 'suspect'. If there are 
                  enough of them to indicate that an antenna or baseline
                  quadrant is bad then all channel/baselines in that
                  quadrant will be flagged.
    default: 8.0

fbq_antenna_frac_limit -- If flag_bad_quarant is True and the fraction
                          of suspect channel/baselines in a particular
                          antenna/quadrant exceeds fbq_antenna_frac_limit
                          then all data for that antenna/quadrant will
                          be flagged.
    default: 0.2

fbq_baseline_frac_limit -- If flag_bad_quarant is True and the fraction
                           of suspect channel/baselines in a particular
                           baseline/quadrant exceeds fbq_baseline_frac_limit
                           then all data for that baseline/quadrant will
                           be flagged.
    default: 1.0 (i.e. no flagging)

---- pipeline context defined parameter arguments which can be set only in
'interactive mode'

vis -- List of input measurement sets.
    default: [] - Use the measurement sets currently known to the pipeline
    context. 

-- Pipeline task execution modes

dryrun -- Run the commands (True) or generate the commands to be run but
          do not execute (False).
    default: True

acceptresults -- This parameter has no effect. The Tsyscal file is already
                 in the pipeline context and is flagged in situ.

Output:

results -- If pipeline mode is 'getinputs' then None is returned. Otherwise
    the results object for the pipeline task is returned.


Examples:

1. Flag bad quadrants and wild outliers, default method.

   hif_rawflagchans()
       equivalent to:
   hif_rawflagchans(flag_hilo=True, fhl_limit=20,
     flag_bad_quadrant=True, fbq_hilo_limit=8, 
     fbq_antenna_frac_limit=0.2, fbq_baseline_frac_limit=1.0)

</example> 

</task>
</casaxml>

=== radio-astro/casa/swig/bindings/tasks/fixvis.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>

<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<!-- Documentation here.                                                -->

<task type="function" name="fixvis" category="editing, manipulation" >

<shortdescription>Recalculates (u, v, w) and/or changes Phase Center </shortdescription>
<description>
Recalculates (u, v, w) and/or changes Phase Center
</description>

<input>
    <param type="string" name="vis" kind="ms" mustexist="true">
        <description>Name of the input visibility set.</description>
        <value></value>
        <example>vis='ngc5921.ms'</example>
    </param>
    <param type="string" name="outputvis" kind="ms">
        <description>Name of the output visibility set.  (Can be the same as vis.)</description>
        <value></value>
        <example>vis='ngc5921\_fixedvis.ms'</example>
    </param>
    <param type="any" direction="in" name="field">
      <description>Fields to operate on.  '' = all.</description>
      <any type="variant"/>
      <value>""</value>
    </param>
<!--    <param type="any" direction="in" name="observation">
      <description>Observation ID(s) to operate on.  '' = all.</description>
      <any type="string int"/>
      <value type="string"></value>
    </param> -->
    <param type="string" name="refcode">
      <description>reference frame to convert UVW coordinates to</description>
      <value></value>
    </param>
    <param type="bool" name="reuse">
      <description>base UVW calculation on the old values?</description>
      <value>True</value>
    </param>
    <param type="string" name="phasecenter">
      <description>use this direction as phase center</description>
      <value></value>
    </param>
    <param type="string" name="datacolumn">
      <description>when applying a phase center shift, modify visibilities only in this/these column(s)</description>
      <value>all</value>
    </param>

</input>

<example>

If the phase center is changed, the corresponding modifications are applied to the 
visibility columns given by the parameter "datacolumn" which is by default set 
to "all" (DATA, CORRECTED, and MODEL).

    Input Parameters
    vis        -- Name of the input visibility set
    
    outputvis  -- Name of the output visibility set, default: same as vis

    field      -- field selection string

    refcode    -- Reference frame to convert to, default: the refcode of PHASE_DIR in the 
                  FIELD table
                  example: 'B1950'
    
    reuse      -- base recalculation on existing UVW coordinates? default=True
                  ignored if parameter 'phasecenter' is set

    phasecenter  --  if set to a valid direction: change the phase center for the given 
                     field to this value
	       example: 'J2000 9h25m00s -05d12m00s'
               If given without the equinox, e.g. '0h01m00s +00d12m00s', the parameter
               is interpreted as a pair of offsets in RA and DEC to the present 
               phasecenter. The RA offset can be given in units of time or angle. If given 
               as a time, it is applied as is. If given as an angle, it is corrected for 
               the cos(DEC) before it is applied.

    datacolumn -- when applying a phase center shift, modify visibilities only in 
                  this/these column(s)
                  default: 'all' (DATA, CORRECTED, and MODEL)
                  example: 'DATA,CORRECTED' (will not modify MODEL)
	       
    Examples:

    fixvis('NGC3256.ms','NGC3256-fixed.ms')
          will recalculate the UVW coordinates for all fields based on the existing
          phase center information in the FIELD table.

    fixvis('Moon.ms','Moon-fixed.ms','Moon', '', 'J2000 9h25m00s 05d12m00s')
          will set the phase center for field 'Moon' to the given direction and recalculate
          the UVW coordinates.

</example>

</task>

</casaxml>

=== radio-astro/casa/gcwrap/tools/singledish/singledishms.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/tools/xml/casa.xsd">


   <tool name="singledishms" module="singledishms">
   <shortdescription>New single dish tool interface to process an MS</shortdescription>


<code>
	<include>tools/singledish/singledishms_forward.h</include>
<private>
	<include>tools/singledish/singledishms_private.h</include>
</private>
</code>
 
   <method type="constructor" name="singledishms">
   <shortdescription>Construct singledishms tool</shortdescription>
   
<description>
This is used to construct an {\tt singledishms} tool.
</description>
<input>
</input>
<returns type="singledishms"/>
<example>
Manual tool construction is done this way:

ssd = casac.singledishms()

</example>
</method>

<method type="function" name="open">
   <shortdescription>Open a new MeasurementSet for processing after closing current MeasurementSet
   </shortdescription>
<description>
Close the current MeasurementSet and open a new MeasurementSet
instead. The current state of {\tt sdms} is retained, except for
the data selection.
</description>
<input>
     <param type="string" name="ms_name">
     <description>New MeasurementSet to be processed</description>
     <value></value>
     </param>
</input>
<returns type="bool">
</returns>
<example>
sdms.open('m100_sd.ms')
</example>
</method>

<method type="function" name="close">
   <shortdescription>Close the {\tt sdms} tool, with data written on disk, keeping sdms running for future use
   </shortdescription>
   <description>
This is used to close {\tt sdms} tools. Note that the
data is written to disk and detached from {\tt sdms} tool.
This is a synonym for done.
   </description>
   <returns type="bool"/>
   <example>
sdms.close()
   </example>
</method>

<method type="function" name="done">
  <shortdescription>Close the {\tt sdms} tool</shortdescription>

  <description>
This is used to close and {\tt sdms} tools. Note that the
data is written to disk  and detached from {\tt sdms} tool.
This is a synonym for close.
  </description>
  <returns type="bool"></returns>
   <example>
sdms.done()
   </example>
</method>

<method type="function" name="name">
  <shortdescription>Provide the name of the attached MeasurementSet</shortdescription>
  <description>
    Returns the name of the attached MeasurementSet.
  </description>
  <returns type="string"/>
  <example>
sdms.name()
  </example>
</method>

<method type="function" name="scale">
  <shortdescription>Multiply a scaling factor to spectra
  </shortdescription>
  <description>
Multipy a scaling factor to selected spectra.
  </description>
  <input>

    <param type="float" name="factor">
      <description>the scaling factor</description>
      <value>1.0</value>
    </param>

  </input>
  <returns type="bool"/>
  <example>
sdms.open('m100_sd.ms')
sdms.set_selection(field='M100')
sdms.scale(factor=2.0)
  </example>
</method>

<method type="function" name="set_selection">
  <shortdescription>Select Measurementset to process</shortdescription>
  
  <description>

  </description>
  <input>
    
      <param type="any" name="spw">
     <description>Spectral Window Ids (0 relative) to select; -1 interpreted as all</description>
     <any type="variant"/>
     <value></value>
     </param>

     <param type="any" name="field">
     <any type="variant"/>
     <description>Field Ids (0 relative) or Field names (msselection syntax and wilcards are used) to select</description>
     <any type="variant"/>
     <value></value>
     </param>

     <param type="any" name="baseline">
     <description>Antenna Ids (0 relative) or Antenna names (msselection syntax and wilcards are used) to select</description>
     <any type="variant"/>
     <value></value>
     </param>

     <param type="any" name="time">
     <description>Limit data selected to be within a given time range. Syntax is the defined in the msselection link</description>
     <any type="variant"/>
     <value></value>
     </param>

     <param type="any" name="scan">
     <description>Limit data selected on scan numbers. Syntax is the defined in the msselection link</description>
     <any type="variant"/>
     <value></value>
     </param>
     
     <param type="any" name="observation">
     <description>Select data by observation ID(s).  The syntax is the same as for scan numbers.</description>
     <any type="variant"/>
     <value></value>
     </param>
     
     <param type="any" name="polarization">
     <description>Select data by polarization(s).</description>
     <any type="variant"/>
     <value></value>
     </param>
     
     <param type="any" name="beam">
     <description>Beam Ids (0 relative) to select; CURRENTLY NOT AVAILABLE!!!</description>
     <any type="variant"/>
     <value></value>
     </param>

     <param type="string" name="taql">
     <description>For the TAQL experts, flexible data selection using the TAQL syntax</description>
     <value></value>
     </param>
 
  </input>
  <returns type="bool"/>
  <example>
sdms.set_selection(field="M100", spw="3,5")
  </example>
</method>

</tool>
</casaxml>
