=== radio-astro/casa/darwin13port/gcwrap/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://casa.nrao.edu/schema/psetTypes.html" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:editix="http://casa.nrao.edu/schema/psetTypes.html">
	<xsd:element name="casaxml">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="task" maxOccurs="unbounded"/>
				<xsd:element ref="tool" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="tool">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="code" minOccurs="0"/>
				<xsd:element ref="shortdescription"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0"/>
				<xsd:element ref="needs" minOccurs="0"/>
				<xsd:element ref="comment" minOccurs="0"/>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="method" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="module" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="method">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="return" minOccurs="0"/>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="input" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="example">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="returns">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="input">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="description">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="li" minOccurs="0"/>
				<xsd:element ref="B" minOccurs="0"/>
				<xsd:element ref="sup" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="sub" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="I" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="shortdescription">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="allowed" minOccurs="0"/>
				<xsd:element ref="choice" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="range" minOccurs="0"/>
				<xsd:element ref="descrition" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
			<xsd:attribute name="units" type="xsd:string"/>
			<xsd:attribute name="mustexist" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="any">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="limittypes" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="code">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
				<xsd:element ref="private"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="private">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="include" type="xsd:string"/>
	<xsd:element name="keyword" type="xsd:string"/>
	<xsd:element name="choice" type="xsd:string"/>
	<xsd:element name="link">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="anchor" type="xsd:string" use="required"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="return">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="allowed">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="kind" type="xsd:string"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="comments">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="range">
		<xsd:complexType>
			<xsd:attribute name="min" type="xsd:string" use="required"/>
			<xsd:attribute name="max" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="output">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="param" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="sub" type="xsd:string"/>
	<xsd:element name="sup" type="xsd:string"/>
	<xsd:element name="needs" type="xsd:string"/>
	<xsd:element name="comment">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="descrition" type="xsd:string"/>
	<xsd:element name="task">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="shortdescription" maxOccurs="unbounded"/>
				<xsd:element ref="input"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="category" type="xsd:string" use="required"/>
			<xsd:attribute name="visibility" type="xsd:string"/>
			<xsd:attribute name="async" type="xsd:string"/>
			<xsd:attribute name="startup" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="constraints">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="when" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="when">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="notequals" minOccurs="0"/>
				<xsd:element ref="equals" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="equals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="default" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="default">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="notequals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="default" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="em" type="xsd:string"/>
</xsd:schema>

=== radio-astro/casa/pipelineflag-2014-08-19/pipeline/hsd/cli/hsd_inspectdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="hsd_inspectdata" category="pipeline">
<shortdescription>Inspects whole data registered to context</shortdescription>
<description>
</description>
<input>
    <param type="string" name="pipelinemode">
	<description>The pipeline operating mode</description>
	<value>automatic</value>
	<allowed kind="enum">
	    <value>automatic</value>
	    <value>interactive</value>
	    <value>getinputs</value>
	</allowed>
    </param>

    <param type="stringArray" name="infiles" subparam="true">
        <description>List of input files to be inspected (default all)</description>
        <value></value>
    </param>

    <param type="bool" name="dryrun" subparam="true">
	<description>Run the task (False) or display task command (True)</description>
	<value>False</value>
    </param>

    <param type="bool" name="acceptresults" subparam="true">
	<description>Add the results into the pipeline context</description>
	<value>True</value>
    </param>

    <constraints>
	<when param="pipelinemode">
	    <equals type="string" value="automatic">
	    </equals>
	    <equals type="string" value="interactive">
                <default param="infiles"><value type="stringArray"></value></default>
		<default param="dryrun"><value type="bool">False</value></default>
		<default param="acceptresults"><value type="bool">True</value></default>
	    </equals>
	    <equals type="string" value="getinputs">
                <default param="infiles"><value type="stringArray"></value></default>
	    </equals>
	</when>
    </constraints>

</input>

<output>
    <param type="any" name="results">
        <description>The output results object</description>
        <any type="variant"/>
        <value></value>
    </param>
</output>
<returns type="void"/>


<example>
The hsd_inspectdata task inspects the data registered to the context. 
All the data must be imported via hsd_importdata task before inspection.

If this task is executed several times, inspection will be done from 
scratch, and previous inspection will be discarded.

Keyword arguments:

---- pipeline parameter arguments which can be set in any pipeline mode

pipelinemode -- The pipeline operating mode. In 'automatic' mode the pipeline
   determines the values of all context defined pipeline inputs
   automatically.  In 'interactive' mode the user can set the pipeline
   context defined parameters manually.  In 'getinputs' mode the user
   can check the settings of all pipeline parameters without running
   the task.
   default: 'automatic'.

---- pipeline context defined parameter argument which can be set only in
'interactive mode'

infiles -- List of data files. These must be a name of Scantables that 
   are registered to context via hsd_importdata task.
   default: []
   example: vis=['X227.PM01.asap', 'X227.PM02.asap']

--- pipeline task execution modes

dryrun -- Run the commands (True) or generate the commands to be run but
   do not execute (False).
   default: True

acceptresults -- Add the results of the task to the pipeline context (True) or
   reject them (False).
   default: True

Output:

results -- If pipeline mode is 'getinputs' then None is returned. Otherwise
   the results object for the pipeline task is returned.


Examples

1. Import data via hsd_importdata task and inspect them.

   hsd_importdata (infiles=['../rawdata/uid___A002_X30a93d_X43e',
                '../rawdata/uid_A002_x30a93d_X44e'])
   hsd_inspectdata()

2. Import data via hsd_importdata task and inspect some of them

   hsd_importdata (infiles=['../rawdata/uid___A002_X30a93d_X43e',
                '../rawdata/uid_A002_x30a93d_X44e'])
   hsd_inspectdata(infiles=['uid___A002_X30a93d_X43e.PM01.asap',
                            'uid___A002_X30a93d_X44e.PM01.asap'])

</example>
</task>
</casaxml>

=== radio-astro/casa/gcwrap/tasks/listfits.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
      file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="listfits" category="information">
	<shortdescription>List the HDU and typical data rows of a fits file:</shortdescription>
	<description>
	List the HDU and typical data rows of a fits file:
	The list will be given in the logger.
	</description>
	<input>
		<param type="string" name="fitsfile" mustexist="true">
			<description>Name of input fits file</description>
			<value></value>
		</param>
	</input>
<returns type="void"/>

<example>

	The HDU and typical data rows in a fits file are listed in the logger.

	Keyword arguments:
	fitsfile -- Name of input fits file 
		default: none; example: fitsfile='ngc5921.uvfits'
        async -- Run asynchronously 
  		default = False; do not run asychronously
 </example>
 </task>
 </casaxml>

=== radio-astro/casa/pipeline_flagging_2015-06-08/pipeline/hifv/cli/hifv_hflag.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="hifv_hflag" category="pipeline">
<shortdescription>Runs gaincurves, opacities, and requantizer gains</shortdescription>
<description>
</description>
<input>
    <param type="stringArray" name="vis" subparam="true">
	<description>List of input visibility data</description>
	<value></value>
    </param>



    <param type="string" name="pipelinemode">
	<description>The pipeline operating mode</description>
	<value>automatic</value>
	<allowed kind="enum">
	    <value>automatic</value>
	    <value>interactive</value>
	    <value>getinputs</value>
	</allowed>
    </param>

    <param type="bool" name="dryrun" subparam="true">
	<description>Run the task (False) or display task command (True)</description>
	<value>False</value>
    </param>

    <param type="bool" name="acceptresults" subparam="true">
	<description>Add the results into the pipeline context</description>
	<value>True</value>
    </param>

    <constraints>
	<when param="pipelinemode">
	    <equals type="string" value="automatic">
	    </equals>
	    <equals type="string" value="interactive">
                <default param="vis"><value type="stringArray"></value></default>
		<default param="dryrun"><value type="bool">False</value></default>
		<default param="acceptresults"><value type="bool">True</value></default>
	    </equals>
	    <equals type="string" value="getinputs">
                <default param="vis"><value type="stringArray"></value></default>
	    </equals>
	</when>
    </constraints>

</input>

<output>
    <param type="any" name="results">
        <description>The output results object</description>
        <any type="variant"/>
        <value></value>
    </param>
</output>
<returns type="void"/>


<example>
The hifv_hflag performs heuristic flagging.  This is includes
a number of test calibrations and iterations of flagging.

Keyword arguments:

---- pipeline parameter arguments which can be set in any pipeline mode

vis -- List of visisbility  data files. These may be ASDMs, tar files of ASDMs,
   MSs, or tar files of MSs, If ASDM files are specified, they will be
   converted  to MS format.
   default: []
   example: vis=['X227.ms', 'asdms.tar.gz']




pipelinemode -- The pipeline operating mode. In 'automatic' mode the pipeline
   determines the values of all context defined pipeline inputs
   automatically.  In 'interactive' mode the user can set the pipeline
   context defined parameters manually.  In 'getinputs' mode the user
   can check the settings of all pipeline parameters without running
   the task.
   default: 'automatic'.

---- pipeline context defined parameter argument which can be set only in
'interactive mode'


--- pipeline task execution modes

dryrun -- Run the commands (True) or generate the commands to be run but
   do not execute (False).
   default: True

acceptresults -- Add the results of the task to the pipeline context (True) or
   reject them (False).
   default: True

Output:

results -- If pipeline mode is 'getinputs' then None is returned. Otherwise
   the results object for the pipeline task is returned.


Examples

1. Load an ASDM list in the ../rawdata subdirectory into the context.

   hifv_hflag()


</example>
</task>
</casaxml>

=== radio-astro/casa/Pipeline-CASA54-P2-B/pipeline/hsd/cli/hsd_restoredata.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="hsd_restoredata" category="pipeline">
<shortdescription>Restore flagged and calibration single dish data from a pipeline run</shortdescription>
<description>
</description>
<input>
    <param type="stringArray" name="vis">
	<description>List of input visibility data</description>
	<value></value>
    </param>

    <param type="stringArray" name="session">
	<description>List of sessions one per visibility file</description>
	<value></value>
    </param>

    <param type="string" name="products_dir">
	<description>The archived pipeline data products directory</description>
	<value>../products</value>
    </param>

    <param type="bool" name="copytoraw">
	<description>Copy calibration and flagging tables to raw data directory</description>
	<value>True</value>
    </param>

    <param type="string" name="rawdata_dir">
	<description>The raw data directory</description>
	<value>../rawdata</value>
    </param>

    <param type="bool" name="lazy">
	<description>Use the lazy filler option</description>
	<value>False</value>
    </param>

    <param type="bool" name="bdfflags">
	<description>Set the BDF flags</description>
	<value>True</value>
    </param>

    <param type="string" name="ocorr_mode">
	<description>Correlation import mode</description>
	<value>ao</value>
    </param>

    <param type="string" name="asis">
	<description>List of tables to import asis</description>
	<value>SBSummary ExecBlock Antenna Station Receiver Source CalAtmosphere CalWVR</value>
    </param>

    <param type="string" name="pipelinemode">
	<description>The pipeline operating mode</description>
	<value>automatic</value>
	<allowed kind="enum">
	    <value>automatic</value>
	    <value>interactive</value>
	    <value>getinputs</value>
	</allowed>
    </param>

    <param type="bool" name="dryrun" subparam="true">
	<description>Run the task (False) or display task command (True)</description>
	<value>False</value>
    </param>

    <param type="bool" name="acceptresults" subparam="true">
	<description>Add the results into the pipeline context</description>
	<value>True</value>
    </param>

    <constraints>
	<when param="pipelinemode">
	    <equals type="string" value="automatic">
	    </equals>
	    <equals type="string" value="interactive">
		<default param="dryrun"><value type="bool">False</value></default>
		<default param="acceptresults"><value type="bool">True</value></default>
	    </equals>
	    <equals type="string" value="getinputs">
	    </equals>
	</when>
    </constraints>

</input>

<output>
    <param type="any" name="results">
        <description>The output results object</description>
        <any type="variant"/>
        <value></value>
    </param>
</output>
<returns type="void"/>


<example>

The hsd_restoredata task restores flagged and calibrated MeasurementSets
from archived ASDMs and pipeline flagging and calibration date products. 

Keyword arguments:

---- pipeline parameter arguments which can be set in any pipeline mode

pipelinemode -- The pipeline operating mode. In 'automatic' mode the pipeline
   determines the values of all context defined pipeline inputs automatically.
   In 'interactive' mode the user can set the pipeline context defined
   parameters manually.  In 'getinputs' mode the user can check the settings
   of all pipeline parameters without running the task.
   default: 'automatic'.

---- pipeline context defined parameter argument which can be set only in
'interactive mode'

vis -- List of raw visibility data files to be restored. Assumed to be
   in the directory specified by rawdata_dir.
   default: None
   example: vis=['uid___A002_X30a93d_X43e']

session -- List of sessions one per visibility file. 
   default: []
   example: session=['session_3']

products_dir -- Name of the data products directory. Currently not
   used.
   default: '../products'
   example: products_dir='myproductspath'
   
copytoraw -- Copy calibration and flagging tables to raw data directory.
   default: True
   example: copytoraw=False

rawdata_dir -- Name of the raw data directory. 
   default: '../rawdata'
   example: rawdata_dir='myrawdatapath'

lazy -- Use the lazy filler option
   default: False
   example: lazy=True

bdfflags -- Set the BDF flags
   default: True
   example: bdfflags=False

ocorr_mode -- Set ocorr_mode
   default: 'ca'
   example: ocorr_mode='ca'

asis -- Set list of tables to import as is
   default: 'Antenna Station Receiver Source CalAtmosphere CalWVR'
   example: asis='Source Receiver'


--- pipeline task execution modes

dryrun -- Run the commands (True) or generate the commands to be run but
   do not execute (False).
   default: True

acceptresults -- Add the results of the task to the pipeline context (True) or
   reject them (False).
   default: True

Output:

results -- If pipeline mode is 'getinputs' then None is returned. Otherwise
   the results object for the pipeline task is returned.

Description

The hsd_restoredata task restores flagged and calibrated data from archived
ASDMs and pipeline flagging and calibration data products. Pending archive
retrieval support hsd_restoredata assumes that the required products
are available in the rawdata_dir in the format produced by the
hifa_exportdata task.

hsd_restoredata assumes that the following entities are available in the raw
data directory

o the ASDMs to be restored
o for each ASDM in the input list
   o a compressed tar file of the final flagversions file, e.g.  
     uid___A002_X30a93d_X43e.ms.flagversions.tar.gz
   o a text file containing the applycal instructions, e.g.
     uid___A002_X30a93d_X43e.ms.calapply.txt
   o a compressed tar file containing the caltables for the parent session,
     e.g. uid___A001_X74_X29.session_3.caltables.tar.gz

hsd_restoredata performs the following operations

o imports the ASDM(s))
o removes the default MS.flagversions directory created by the filler
o restores the final MS.flagversions directory stored by the pipeline
o restores the final set of pipeline flags to the MS
o restores the final calibration state of the MS
o restores the final calibration tables for each MS
o applies the calibration tables to each MS


Issues

Examples

1. Restore the pipeline results for a single ASDM in a single session 

    hsd_restoredata (vis=['uid___A002_X30a93d_X43e'], session=['session_1'], ocorr_mode='ao')

</example>
</task>
</casaxml>
